# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import MySQLdb as mysql
from homepage import Ui_homepage

class Homepage(QtWidgets.QMainWindow, Ui_homepage):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowTitle("HOME SCREEN")
        
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 545)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 545))
        MainWindow.setMaximumSize(QtCore.QSize(400, 545))
        MainWindow.setStyleSheet("background-color:white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 401, 545))
        self.label.setStyleSheet("border-image: url(:/image_widget/images/bgdimage6.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 30, 101, 31))
        self.label_2.setStyleSheet("font:bold 20pt;color: black; background:none;")
        self.label_2.setIndent(10)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 90, 111, 101))
        self.label_3.setStyleSheet("border-image: url(:/image_widget/images/bgdimage7.jpeg); border-radius: 40px ; border:1px solid black;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 240, 81, 19))
        self.label_4.setStyleSheet("color: black; font: 15pt bold; background:none;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 290, 111, 21))
        self.label_5.setStyleSheet("color: black; font:15pt bold; background:none;\n"
"")
        self.label_5.setObjectName("label_5")
        self.nameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameEdit.setGeometry(QtCore.QRect(150, 240, 181, 27))
        self.nameEdit.setStyleSheet("border-radius:10px; color:black;")
        self.nameEdit.setText("")
        self.nameEdit.setObjectName("nameEdit")
        self.passEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.passEdit.setGeometry(QtCore.QRect(150, 290, 181, 27))
        self.passEdit.setStyleSheet("border-radius:10px; color:black;")
        self.passEdit.setText("")
        self.passEdit.setFrame(True)
        self.passEdit.setObjectName("passEdit")
        self.loginBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loginBtn.setGeometry(QtCore.QRect(160, 350, 81, 27))
        self.loginBtn.setStyleSheet("color:black; background-color:    #0077E2; border-radius: 10px;")
        self.loginBtn.setObjectName("loginBtn")
        self.cancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBtn.setGeometry(QtCore.QRect(260, 350, 71, 27))
        self.cancelBtn.setStyleSheet("color:black; background-color:red; border-radius: 10px;")
        self.cancelBtn.setObjectName("cancelBtn")
        self.forgotpwdBtn = QtWidgets.QPushButton(self.centralwidget)
        self.forgotpwdBtn.setGeometry(QtCore.QRect(30, 420, 171, 27))
        self.forgotpwdBtn.setStyleSheet("color:white; font: 12pt; background-color: #0077E2; border-radius: 10px;")
        self.forgotpwdBtn.setObjectName("forgotpwdBtn")
        self.createAcctBtn = QtWidgets.QPushButton(self.centralwidget)
        self.createAcctBtn.setGeometry(QtCore.QRect(210, 420, 171, 27))
        self.createAcctBtn.setStyleSheet("color:white; font: 12pt bold; background-color: #0077E2; border-radius:10px;")
        self.createAcctBtn.setObjectName("createAcctBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
                   
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "LOGIN"))
        self.label_4.setText(_translate("MainWindow", "Name :"))
        self.label_5.setText(_translate("MainWindow", "Password : "))
        self.loginBtn.setText(_translate("MainWindow", "Login"))
        self.cancelBtn.setText(_translate("MainWindow", "Cancel"))
        self.forgotpwdBtn.setText(_translate("MainWindow", "Forgot password?"))
        self.createAcctBtn.setText(_translate("MainWindow", "Create Account"))
import images
