# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(794, 601)
        self.centralwidget = QtWidgets.QWidget(RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-20, 0, 821, 561))
        self.label.setStyleSheet("background-color:#0077E2;\n"
"background-image: url(:/image_widget/images/bgdimage6.jpg);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lbl_CAccount = QtWidgets.QLabel(self.centralwidget)
        self.lbl_CAccount.setGeometry(QtCore.QRect(500, 70, 221, 41))
        self.lbl_CAccount.setStyleSheet("font: 18pt bold;background-color:white;border-radius:10px; color:black;")
        self.lbl_CAccount.setIndent(20)
        self.lbl_CAccount.setObjectName("lbl_CAccount")
        self.lbl_Name = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Name.setGeometry(QtCore.QRect(460, 130, 121, 16))
        self.lbl_Name.setStyleSheet("font: 15pt bold;color:black;")
        self.lbl_Name.setObjectName("lbl_Name")
        self.nameAEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameAEdit.setGeometry(QtCore.QRect(480, 150, 261, 31))
        self.nameAEdit.setStyleSheet("border-radius: 10px; background-color:white;")
        self.nameAEdit.setText("")
        self.nameAEdit.setObjectName("nameAEdit")
        self.emailEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.emailEdit.setGeometry(QtCore.QRect(480, 220, 261, 31))
        self.emailEdit.setStyleSheet("border-radius: 10px; background-color: white;")
        self.emailEdit.setObjectName("emailEdit")
        self.passwordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordEdit.setGeometry(QtCore.QRect(480, 290, 261, 31))
        self.passwordEdit.setStyleSheet("background-color: white;border-radius:10px;")
        self.passwordEdit.setObjectName("passwordEdit")
        self.CpasswordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.CpasswordEdit.setGeometry(QtCore.QRect(480, 370, 261, 31))
        self.CpasswordEdit.setStyleSheet("background-color:white;border-radius:10px;")
        self.CpasswordEdit.setObjectName("CpasswordEdit")
        self.registerBtn = QtWidgets.QPushButton(self.centralwidget)
        self.registerBtn.setGeometry(QtCore.QRect(460, 510, 321, 31))
        self.registerBtn.setStyleSheet("border-radius:10px; font:14pt bold;background-color:#0077E2;color:black;")
        self.registerBtn.setObjectName("registerBtn")
        self.lbl_Email = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Email.setGeometry(QtCore.QRect(460, 200, 81, 16))
        self.lbl_Email.setStyleSheet("font: 15pt bold; color:black;")
        self.lbl_Email.setObjectName("lbl_Email")
        self.lbl_Password = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Password.setGeometry(QtCore.QRect(460, 270, 121, 16))
        self.lbl_Password.setStyleSheet("color:black; font:15pt bold;")
        self.lbl_Password.setObjectName("lbl_Password")
        self.lbl_CPassword = QtWidgets.QLabel(self.centralwidget)
        self.lbl_CPassword.setGeometry(QtCore.QRect(460, 340, 201, 16))
        self.lbl_CPassword.setStyleSheet("font:15pt bold; color:black;")
        self.lbl_CPassword.setObjectName("lbl_CPassword")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(420, 60, 20, 501))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 20, 801, 31))
        self.label_2.setStyleSheet("color:black;background-color:white;font: 18pt bold;")
        self.label_2.setIndent(130)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 381, 491))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background-image:url(:/image_widget/images/bgdimage2.jpeg);border-radius:20px; background-color:white; repeat: none;\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.statuslbl = QtWidgets.QLabel(self.centralwidget)
        self.statuslbl.setGeometry(QtCore.QRect(460, 410, 111, 31))
        self.statuslbl.setStyleSheet("font:15pt bold; color:black;")
        self.statuslbl.setObjectName("statuslbl")
        self.statusEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.statusEdit.setGeometry(QtCore.QRect(480, 440, 261, 31))
        self.statusEdit.setStyleSheet("background-color:white;border-radius:10px;")
        self.statusEdit.setObjectName("statusEdit")
        RegisterWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RegisterWindow)
        self.statusbar.setObjectName("statusbar")
        RegisterWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)
        
        
        def register(self):
                host = '127.0.0.1'
                user = 'root'
                password = ''
        
                        try:
                                nameA = self.nameAEdit.text()
                                email = self.emailEdit.text()
                passE = self.passwordEdit.text()
                CpassE = self.CpasswordEdit.text()
                status = self.statusEdit.text()
                self.registerBtn.clicked.connect(self.registration)
                
                mydb = mysql.connect(host,user,password)
                cur = mydb.cursor()
            
                cur.execute('show databases')
                print(cur.fetchall())
            
                db_select = 'use DIMS'
                cur.execute(db_select) 
                
                tb_create = "create table Register(email varchar(50),status varchar(15))"
                
                insert_into_Registertb = "insert into Register (email,status) values (%s,%s)"
                data = [(email,status)]
                cur.execute(insert_into_Registertb,data)
                mydb.commit()
                
                insert_into_logintb = "insert into login(username,password) values (%s,%s)"
                data_login = [(nameA,passE)]
                cur.execute(insert_into_logintb,data_login)
                mydb.commit()
                
                desc_Rtb = "desc Register"
                cur.excute(desc_Rtb)
                print(cur.fetchall())
                
                desc_Ltb = "desc login"
                cur.execute(desc_Ltb)
                print(cur.fetchall())
                
                print("data saved to the database")
            except mysql.Error:
                print("Failed to connect the database")
    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "MainWindow"))
        self.lbl_CAccount.setText(_translate("RegisterWindow", "Create Account"))
        self.lbl_Name.setText(_translate("RegisterWindow", "Name :"))
        self.registerBtn.setText(_translate("RegisterWindow", "Register"))
        self.lbl_Email.setText(_translate("RegisterWindow", "Email :"))
        self.lbl_Password.setText(_translate("RegisterWindow", "Password :"))
        self.lbl_CPassword.setText(_translate("RegisterWindow", "Confirm Password :"))
        self.label_2.setText(_translate("RegisterWindow", "DRUG INVENTORY MANAGEMENT SYSTEM"))
        self.statuslbl.setText(_translate("RegisterWindow", "Status :"))
import images
